// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    public partial class Author
    {
        public Author()
        {
            BookAuthor = new HashSet<BookAuthor>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(64)]
        [Column(TypeName="nvarchar")]
        public string Name { get; set; }
        [Required]
        [StringLength(128)]
        [Column(TypeName = "nvarchar")]
        public string Surname { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfBirth { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfDeath { get; set; }
        [StringLength(2000)]
        public string ImageUrl { get; set; }
        [Required]
        [StringLength(2000)]
        public string Bio { get; set; }
        [Required]
        [StringLength(255)]
        public string PlaceOfBirth { get; set; }
        [InverseProperty("Author")]
        public virtual ICollection<BookAuthor> BookAuthor { get; set; }
    }
}