// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    [Index(nameof(Series_Id), Name = "ISPARTOFSERIES_FK")]
    public partial class Book
    {
        public Book()
        {
            BookAuthor = new HashSet<BookAuthor>();
            BookIssue = new HashSet<BookIssue>();
            BookTag = new HashSet<BookTag>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(256)]
        [Column(TypeName ="nvarchar")]
        public string OriginalTitle { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ReleaseDate { get; set; }
        public int ReleaseYearOnly { get; set; }
        public int? Series_Id { get; set; }
        public int? OrderInSeries { get; set; }

        [ForeignKey(nameof(Series_Id))]
        [InverseProperty("Book")]
        public virtual Series Series { get; set; }
        [InverseProperty("Book")]
        public virtual ICollection<BookAuthor> BookAuthor { get; set; }
        [InverseProperty("Book")]
        public virtual ICollection<BookIssue> BookIssue { get; set; }
        [InverseProperty("Book")]
        public virtual ICollection<BookTag> BookTag { get; set; }
    }
}