// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    [Index(nameof(Edition_Id), Name = "EDITIONOFISSE_FK")]
    [Index(nameof(Book_Id), nameof(BookIssue_id), Name = "ISSUEINEDITION_FK")]
    public partial class BookIssueInEdition
    {
        [Key]
        public int Edition_Id { get; set; }
        [Key]
        public int Book_Id { get; set; }
        [Key]
        public int BookIssue_id { get; set; }
        public int OrderInEdition { get; set; }

        [ForeignKey("Book_Id,BookIssue_id")]
        [InverseProperty(nameof(BookIssue.BookIssueInEdition))]
        public virtual BookIssue Book { get; set; }
        [ForeignKey(nameof(Edition_Id))]
        [InverseProperty(nameof(BookEdition.BookIssueInEdition))]
        public virtual BookEdition Edition { get; set; }
    }
}