// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    [Index(nameof(Tag_Id), Name = "BOOKHASTAG_FK")]
    [Index(nameof(Book_Id), Name = "TAGGEDBOOKIS_FK")]
    public partial class BookTag
    {
        [Key]
        public int Book_Id { get; set; }
        [Key]
        public int Tag_Id { get; set; }

        [ForeignKey(nameof(Book_Id))]
        [InverseProperty("BookTag")]
        public virtual Book Book { get; set; }
        [ForeignKey(nameof(Tag_Id))]
        [InverseProperty("BookTag")]
        public virtual Tag Tag { get; set; }
    }
}