// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    [Index(nameof(Book_Id), nameof(BookIssue_Id), Name = "BOOKONBOOKSHELF_FK")]
    [Index(nameof(User_Id), nameof(BookShelf_Id), Name = "ONBOOKSHELF_FK")]
    public partial class BookOnBookshelf
    {
        [Key]
        public string User_Id { get; set; }
        [Key]
        public int BookShelf_Id { get; set; }
        [Key]
        public int Book_Id { get; set; }
        [Key]
        public int BookIssue_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateAdded { get; set; }
        [StringLength(4000)]
        public string Comment { get; set; }

        [ForeignKey("Book_Id,BookIssue_Id")]
        [InverseProperty(nameof(BookIssue.BookOnBookshelf))]
        public virtual BookIssue Book { get; set; }
        [ForeignKey("User_Id,BookShelf_Id")]
        [InverseProperty("BookOnBookshelf")]
        public virtual UserBookShelf UserBookShelf { get; set; }
    }
}