// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    [Index(nameof(Book_Id), Name = "AUTHOROF_FK")]
    [Index(nameof(Author_Id), Name = "WRITTENBY_FK")]
    public partial class BookAuthor
    {
        [Key]
        public int Author_Id { get; set; }
        [Key]
        public int Book_Id { get; set; }

        [ForeignKey(nameof(Author_Id))]
        [InverseProperty("BookAuthor")]
        public virtual Author Author { get; set; }
        [ForeignKey(nameof(Book_Id))]
        [InverseProperty("BookAuthor")]
        public virtual Book Book { get; set; }
    }
}