// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    [Index(nameof(ReadingChallange_Id), Name = "BOOKINCHALANGE_FK")]
    [Index(nameof(Book_Id), nameof(BookIssue_Id), Name = "CHALLANGEISSUE_FK")]
    public partial class BookInReadingChallange
    {
        [Key]
        public int Book_Id { get; set; }
        [Key]
        public int BookIssue_Id { get; set; }
        [Key]
        public int ReadingChallange_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FinishedOn { get; set; }
        [StringLength(4000)]
        public string UserComment { get; set; }

        [ForeignKey("Book_Id,BookIssue_Id")]
        [InverseProperty(nameof(BookIssue.BookInReadingChallange))]
        public virtual BookIssue Book { get; set; }
        [ForeignKey(nameof(ReadingChallange_Id))]
        [InverseProperty("BookInReadingChallange")]
        public virtual ReadingChallange ReadingChallange { get; set; }
    }
}