// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    [Index(nameof(Book_Id), nameof(BookIssue_Id), Name = "CURRENTLYREADINGBOOK_FK")]
    [Index(nameof(User_Id), Name = "CURRENTLYREADINGBY_FK")]
    public partial class CurrentlyReading
    {
        [Key]
        public string User_Id { get; set; }
        [Key]
        public int Book_Id { get; set; }
        [Key]
        public int BookIssue_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddedOn { get; set; }
        public int? PagesRead { get; set; }

        [ForeignKey("Book_Id,BookIssue_Id")]
        [InverseProperty(nameof(BookIssue.CurrentlyReading))]
        public virtual BookIssue Book { get; set; }
    }
}