// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    public partial class Language
    {
        public Language()
        {
            BookIssue = new HashSet<BookIssue>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string EnglishName { get; set; }
        [Required]
        [StringLength(200)]
        public string NativeName { get; set; }
        [Required]
        [StringLength(10)]
        public string LocalizationCode { get; set; }

        [InverseProperty("Language")]
        public virtual ICollection<BookIssue> BookIssue { get; set; }
    }
}