// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    [Index(nameof(Year_Id), Name = "CHALLANGEFORYEAR_FK")]
    [Index(nameof(User_Id), Name = "OFUSER_FK")]
    public partial class ReadingChallange
    {
        public ReadingChallange()
        {
            BookInReadingChallange = new HashSet<BookInReadingChallange>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string User_Id { get; set; }
        public int Year_Id { get; set; }
        public int BooksPledged { get; set; }

        [ForeignKey(nameof(Year_Id))]
        [InverseProperty("ReadingChallange")]
        public virtual Year Year { get; set; }
        [InverseProperty("ReadingChallange")]
        public virtual ICollection<BookInReadingChallange> BookInReadingChallange { get; set; }
    }
}