// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    [Index(nameof(CommentAuthor_Id), Name = "COMMENTBY_FK")]
    [Index(nameof(Book_Id), nameof(BookIssue_Id), nameof(Review_User_Id), Name = "COMMENTON_FK")]
    public partial class ReviewComment
    {
        public ReviewComment()
        {
            CommentReaction = new HashSet<CommentReaction>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Key]
        public int Book_Id { get; set; }
        [Key]
        public int BookIssue_Id { get; set; }
        [Key]
        public string Review_User_Id { get; set; }
        [Key]
        public string CommentAuthor_Id { get; set; }
        [StringLength(4000)]
        [Column(TypeName ="nvarchar")]
        public string Content { get; set; }

        [ForeignKey("Book_Id,BookIssue_Id,Review_User_Id")]
        [InverseProperty("ReviewComment")]
        public virtual Review Review { get; set; }
        [InverseProperty("ReviewComment")]
        public virtual ICollection<CommentReaction> CommentReaction { get; set; }
    }
}