// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    [Index(nameof(Book_Id), nameof(BookIsse_Id), Name = "WANTTOREADBOOK_FK")]
    [Index(nameof(User_Id), Name = "WANTTOREADBY_FK")]
    public partial class WantToRead
    {
        [Key]
        public string User_Id { get; set; }
        [Key]
        public int Book_Id { get; set; }
        [Key]
        public int BookIsse_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddedOn { get; set; }

        [ForeignKey("Book_Id,BookIsse_Id")]
        [InverseProperty(nameof(BookIssue.WantToRead))]
        public virtual BookIssue Book { get; set; }
    }
}