// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BookshelfAPI.Data.Models
{
    public partial class Year
    {
        public Year()
        {
            ReadingChallange = new HashSet<ReadingChallange>();
        }

        [Key]
        public int Id { get; set; }
        [Column("Year")]
        public int Year1 { get; set; }

        [InverseProperty("Year")]
        public virtual ICollection<ReadingChallange> ReadingChallange { get; set; }
    }
}